defaultContentLanguage = "ja"
baseURL = "https://polyscone.jp/"
languageCode = "ja-jp"
title = "Polyscone"

enableRobotsTXT = true
pluralizeListTitles = false
publishDir = "docs"

[params]
	author = "Polyscone"
	tagline = ""
	description = ""

[languages]
	[languages.ja]
		languageName = "日本語"

[markup]
	[markup.highlight]
		codeFences = true
		guessSyntax = false
		hl_Lines = ""
		lineNoStart = 1
		lineNos = false
		lineNumbersInTable = true
		noClasses = true
		style = "tango"
		tabWidth = 4

	[markup.tableOfContents]
		startLevel = 2
		endLevel = 3
		ordered = true
